[package]
name = "symbolic_regression" 
authors = ["Eduardo Guerra"]
version = "0.1.0"
edition = "2021"


[dependencies]
ndarray = "0.15"
rand = "0.8"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"