# Population settings
initial_pop = 1000
min_pop = 1000
max_pop = 20000
max_generations = 500

# Time settings
target_time_secs = 250

# Mutation settings
base_mutation_rate = 0.1
min_mutation = 0.05
max_mutation = 0.1

# Weight settings
error_weight = 0.5
physics_weight = 0.75
rse_weight = 0.25
rmse_weight = 0.25

# Other parameters
initial_physics_ratio = 0.8
stagnation_threshold = 0.2
stagnation_response = 0.5
batch_size = 64

# Physics constants
i_dss = 0.438  # Saturation current (A)
vp = 0.4       # Pinch-off voltage (V)